/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'lena' at '12/10/15 12:56 PM' with Gradle 2.9
 *
 * @author lena, @date 12/10/15 12:56 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
  def anotherLibraryMethod(): String = "Hello World!"
}
